# Generated by Django 5.0.3 on 2024-04-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(blank=True, choices=[('Free', 'Free'), ('Busy', 'Busy'), ('Reserved', 'Reserved')], default='Free', max_length=8)),
                ('room_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview', models.ImageField(upload_to='previews/')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms-img/')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room')),
            ],
        ),
    ]
